# Generated by Django 5.0.4 on 2024-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
