version: '3.10'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY='django-insecure-@weaow$e+fy&lbvg0zklzzkr)9&-+dr-42)!kl!+dcu25y$(5)'
      - DATABASE_URL=sqlite:///db.sqlite3
# В идеале нам нужно брать данные из .env файла

volumes:
  postgres_data:
